---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for Ubuntu and Debian server
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: install apache and php for CentOS Server
    apt:
      name:
        - httpd
        - php
      state: latest
      update_cache:
    when: ansible_distribution = "CentOS"
