---

- hosts: all
  become: true
  tasks:

  - name: update respository index
    apt:
      update_cache: yes

  - name: install apache
    apt:
      name: apache2
      state: latest

  - name: install php 
    apt:
      name: libapache2-mod-php
      state: latest
