---

- hosts: all
  become: true
  tasks:

  - name: update respository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache
    apt:
      name: apache2
      state: absent
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: install php 
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution in ["Ubuntu","Debian"]
