---

- hosts: [web_servers]
  become: true
  tasks:  

  - name: install apache and php for Ubuntu and Debian server
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: changing email id in /usr/sbin/balaji/file.yml
    tags: apache,apache2,ubuntu
    lineinfile:
      path: /usr/sbin/balaji/file.yml
      regexp: '^email'  # regular expression 
      line: email subhashreegr@gmail.com
    when: ansible_distribution in ["Ubuntu","Debian"]
    register: value1

  - name: restarting apache2 after email address has been changed
    tags: apache,apache2,ubuntu
    service:
      name: apache2
      state: restarted
    when: value1.changed

  - name: install apache and php for CentOS Server
    tags: apache2,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache2,centos,httpd 
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

- hosts: [file_servers]
  become: true
  tasks:

  - name: install vim-nox for Ubuntu and Debian server
    tags: ubuntu,vim
    apt:
      name:
        - vim-nox
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: install apache and php for CentOS Server
    tags: centos,vim
    dnf:
      name:
        - mariadb-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"


- hosts: [db_servers]
  become: true
  tasks:
  - name: install samba for Ubuntu and Debian server
    tags: samba,ubuntu
    apt:
      name:
        - samba
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: install samba and php for CentOS Server
    tags: centos,samba
    dnf:
      name:
        - samba
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

 
- hosts: [workstations]
  become: true
  tasks:
  - name: copy default HTML FIle for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index1.html
      owner: root
      group: root
      mode: 0644
  
  - name: install zip
    tags: apache,apache2,httpd 
    package:
      name: unzip
   
  - name: intall terraform 
    tags: apache2,apache,httpd
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip 
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0644
       
