  - name: copy default HTML FIle for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index1.html
      owner: root
      group: root
      mode: 0644

  - name: install zip
    tags: apache,apache2,httpd
    package:
      name: unzip

  - name: intall terraform
    tags: apache2,apache,httpd
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0644
